In [1]:
## Agent

import numpy as np
import pandas as pd


class QLearningTable:
    def __init__(self, actions, learning_rate=0.01, reward_decay=0.9, e_greedy=0.9):
        self.actions = actions  # a list
        self.lr = learning_rate
        self.gamma = reward_decay
        self.epsilon = e_greedy
        self.q_table = pd.DataFrame(columns=self.actions, dtype=np.float64)

    def choose_action(self, observation):
        self.check_state_exist(observation)
        # action selection
        if np.random.uniform() < self.epsilon:
            # choose best action
            state_action = self.q_table.loc[observation, :]
            # some actions may have the same value, randomly choose on in these actions
            action = np.random.choice(state_action[state_action == np.max(state_action)].index)
        else:
            # choose random action
            action = np.random.choice(self.actions)
        return action

    def learn(self, s, a, r, s_):
        self.check_state_exist(s_)
        q_predict = self.q_table.loc[s, a]
        if s_ != 'terminal':
            q_target = r + self.gamma * self.q_table.loc[s_, :].max()  # next state is not terminal
        else:
            q_target = r  # next state is terminal
        self.q_table.loc[s, a] += self.lr * (q_target - q_predict)  # update

    def check_state_exist(self, state):
        if state not in self.q_table.index:
            # append new state to q table
            self.q_table = self.q_table.append(
                pd.Series(
                    [0]*len(self.actions),
                    index=self.q_table.columns,
                    name=state,
                )
            )

In [2]:
import gym
env = gym.make('CartPole-v0')
env = env.unwrapped

print(env.action_space)
print(env.observation_space)
print(env.observation_space.high)
print(env.observation_space.low)

Discrete(2)
Box(4,)
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [3]:
act = [num for num in range(env.action_space.n)]
act

[0, 1]

In [4]:
RL = QLearningTable(actions = act)

In [5]:
RL.actions

[0, 1]

In [6]:
RL.lr

0.01

In [7]:
# 开始训练
observation = env.reset()

In [8]:
observation

array([-0.03735352, -0.04929019,  0.03653114,  0.04005024])

In [16]:
str(observation)

'[-0.03735352 -0.04929019  0.03653114  0.04005024]'

In [19]:
action = RL.choose_action(str(observation))
action

1

In [20]:
observation_, reward, done, info = env.step(action)

In [21]:
print('s_:',observation_)
print('r:',reward)
print(done)
print(info)

s_: [-0.03833932  0.14528938  0.03733215 -0.24088662]
r: 1.0
False
{}


In [11]:
RL.q_table.index

Index([], dtype='object')

In [17]:
RL.check_state_exist(str(observation))

In [13]:
# 建立一个新的对象
RL2 = QLearningTable(actions = act)

In [14]:
RL2.q_table.index

Index([], dtype='object')

In [15]:
type(RL2.q_table.index)

pandas.core.indexes.base.Index

In [ ]:
RL2.q_table.index