In [1]:
import gym

### 选择环境

In [2]:
env = gym.make('CartPole-v0')

### 动作空间、动作值

In [3]:
env.action_space
# The Discrete space allows a fixed range of non-negative numbers, 
# so in this case valid actions are either 0 or 1. 

Discrete(2)

In [4]:
env.action_space.n

2

In [5]:
action = env.action_space.sample()
action

0

### 观测空间、观测值

In [6]:
env.observation_space
# The Box space represents an n-dimensional box, 
# so valid observations will be an array of 4 numbers. 

Box(4,)

In [7]:
env.observation_space.shape

(4,)

In [8]:
env.observation_space.shape[0]

4

In [9]:
env.observation_space.low

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

In [10]:
env.observation_space.high

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

In [30]:
observation = env.reset()  # 启动环境 顺带输出第一个环境观测值
observation

array([ 0.00314633,  0.04438567, -0.0010259 , -0.04520586])

In [34]:
observation, reward, done, info = env.step(action)

array([-0.0058967 , -0.54098007,  0.01379758,  0.83285751])

In [37]:
print('observation:',observation)
print('reward:',reward)
print('done:',done)
print('info:',info)

observation: [-0.0058967  -0.54098007  0.01379758  0.83285751]
reward: 1.0
done: False
info: {}


### 空间：Discrete and Box

In [11]:
# This introspection can be helpful to write generic code that- 
# -works for many different environments.
# Box and Discrete are the most common Spaces. 
# You can sample from a Space or check that something belongs to it

from gym import spaces

In [20]:
space = spaces.Discrete(8)  # Set with 8 elements {0, 1, 2, ..., 7}
space

Discrete(8)

In [23]:
x = space.sample()
x

4

In [26]:
space.contains(x)  # 检查x是否存在于这个空间中

True

In [27]:
space.n == 8   # 检查空间的维度是不是8

True

In [38]:
env.action_space

Discrete(2)

In [51]:
import numpy as np
a = [num for num in range(env.action_space.n)]

In [52]:
a

[0, 1]

In [50]:
range(env.action_space.n)

range(0, 2)

In [53]:
np.arange(env.action_space.n)

array([0, 1])